Update script generation

diff --git a/docker/gs64/launchpad-gem b/docker/gs64/launchpad-gem
--- a/docker/gs64/launchpad-gem
+++ b/docker/gs64/launchpad-gem
@@ -4,15 +4,15 @@
 readonly SYSTEM_USER_PASSWORD="${GS64_SYSTEM_USER_PASSWORD:-swordfish}"
 readonly STONE_NAME="${GS64_STONE_SERVICE_NAME:-gs64stone}"
 
-echo <<EOF >> .topazini
-set gemstone !@${GS64_STONE_HOSTNAME}!${STONE_NAME} user SystemUser pass ${SYSTEM_USER_PASSWORD}
-iferror exit 1
-login
-doit
-    CommandLineHandler activateWith: CommandLineArguments new
-%
-exit 0
-EOF
+set +o histexpand
+echo "set gemstone !@${GS64_STONE_HOSTNAME}!${STONE_NAME} user SystemUser pass ${SYSTEM_USER_PASSWORD}" >> .topazini
+echo "iferror exit 1" >> .topazini
+echo "login" >> .topazini
+echo "doit" >> .topazini
+echo "    CommandLineHandler activateWith: CommandLineArguments new" >> .topazini
+echo "%" >> .topazini
+echo "exit 0" >> .topazini
+set -o histexpand
 
 pid=0
 
